/**
 * Mirrors `test_build_markdown_report_structure` from the legacy test suite,
 * plus the empty-state branches. Pure, offline.
 */

import { describe, expect, it } from "vitest";

import { EXAMPLE_RESULTS } from "@/lib/examples";
import { buildMarkdownReport } from "@/lib/markdown";
import { normalizeResults } from "@/lib/normalize";

const FIXED_DATE = new Date(2026, 6, 16, 9, 5); // 2026-07-16 09:05 local

describe("buildMarkdownReport", () => {
  // test_build_markdown_report_structure
  it("renders every section of a populated report", () => {
    const results = normalizeResults({
      summary: "Sentence one. Sentence two.",
      entities: { companies: ["Acme"], people: [], places: [] },
      metrics: [{ label: "Revenue", value: "$4.2B", change: "+27%" }],
      sentiment: { label: "Positive", confidence_score: 90 },
      topics: ["earnings", "saas"],
    });
    const md = buildMarkdownReport(results);

    expect(md).toContain("# Signal Intelligence Report");
    expect(md).toContain("> Sentence one. Sentence two.");
    expect(md).toContain("| Metric | Value | Change |");
    expect(md).toContain("Acme");
    expect(md).toContain("`#earnings`");
    expect(md).toContain("Positive");
  });

  it("renders the sentiment line with score and band", () => {
    const md = buildMarkdownReport({
      sentiment: { label: "Positive", confidence_score: 90 },
    });
    expect(md).toContain("**Positive** — confidence 90/100 (High)");
  });

  it("italicises the reasoning when present and omits it otherwise", () => {
    const withReason = buildMarkdownReport({
      sentiment: { label: "Neutral", reasoning: "Mixed signals." },
    });
    expect(withReason).toContain("_Mixed signals._");
    expect(buildMarkdownReport({})).not.toContain("__");
  });

  it("groups entities under their headings", () => {
    const md = buildMarkdownReport({
      entities: { companies: ["Acme"], people: ["Dana"], places: ["Brussels"] },
    });
    expect(md).toContain("**Companies**\n- Acme");
    expect(md).toContain("**People**\n- Dana");
    expect(md).toContain("**Places**\n- Brussels");
  });

  it("shows empty states when there is nothing to report", () => {
    const md = buildMarkdownReport({});
    expect(md).toContain("_No named entities found._");
    expect(md).toContain("_No specific metrics found._");
    expect(md).toContain("_No topics identified._");
    expect(md).toContain("No summary was returned.");
  });

  it("em-dashes blank label and change cells in the metrics table", () => {
    const md = buildMarkdownReport({ metrics: ["Strong demand across regions"] });
    expect(md).toContain("| — | Strong demand across regions | — |");
  });

  it("formats the footer timestamp as YYYY-MM-DD HH:MM", () => {
    const md = buildMarkdownReport({}, FIXED_DATE);
    expect(md).toContain("_Generated by Signal • 2026-07-16 09:05_");
    expect(md.trimEnd().endsWith("09:05_")).toBe(true);
  });

  it("normalizes raw input before rendering", () => {
    // A stray string entity + 7 topics must still render legally.
    const md = buildMarkdownReport({
      entities: { companies: "Acme" },
      topics: ["a", "b", "c", "d", "e", "f", "g"],
    });
    expect(md).toContain("- Acme");
    expect(md).toContain("`#a` `#b` `#c` `#d` `#e`");
    expect(md).not.toContain("`#f`");
  });

  it("renders the canned example results", () => {
    const md = buildMarkdownReport(EXAMPLE_RESULTS["📊 Earnings note"], FIXED_DATE);
    expect(md).toContain("| Revenue | $4.2B | +27% |");
    expect(md).toContain("Acme Cloud Inc.");
    expect(md).toContain("**Positive** — confidence 92/100 (High)");
  });
});
