/**
 * Markdown report builder — 1:1 port of `build_markdown_report` from the legacy
 * `utils/constants.py`. Pure. Renders a normalized result as a paste-ready
 * Markdown document (H1, blockquote summary, sentiment line, grouped entity
 * bullets, metrics table, #topic tags, timestamp footer).
 */

import { normalizeResults } from "@/lib/normalize";

/** Format a Date as "YYYY-MM-DD HH:MM" in local time (Python %Y-%m-%d %H:%M). */
function formatTimestamp(when: Date): string {
  const pad = (n: number) => String(n).padStart(2, "0");
  const y = when.getFullYear();
  const mo = pad(when.getMonth() + 1);
  const d = pad(when.getDate());
  const h = pad(when.getHours());
  const mi = pad(when.getMinutes());
  return `${y}-${mo}-${d} ${h}:${mi}`;
}

export function buildMarkdownReport(results: unknown, generatedAt?: Date): string {
  const data = normalizeResults(results);
  const when = generatedAt ?? new Date();
  const lines: string[] = [];

  lines.push("# Signal Intelligence Report");
  lines.push("");
  lines.push("## Executive Summary");
  lines.push(`> ${data.summary}`);
  lines.push("");

  const sent = data.sentiment;
  lines.push("## Sentiment");
  lines.push(
    `**${sent.label}** — confidence ${sent.confidence_score}/100 (${sent.confidence})`,
  );
  if (sent.reasoning) {
    lines.push("");
    lines.push(`_${sent.reasoning}_`);
  }
  lines.push("");

  lines.push("## Key Entities");
  const entities = data.entities;
  let anyEntity = false;
  const groups: [keyof typeof entities, string][] = [
    ["companies", "Companies"],
    ["people", "People"],
    ["places", "Places"],
  ];
  for (const [key, heading] of groups) {
    const items = entities[key];
    if (items.length) {
      anyEntity = true;
      lines.push(`**${heading}**`);
      for (const item of items) {
        lines.push(`- ${item}`);
      }
      lines.push("");
    }
  }
  if (!anyEntity) {
    lines.push("_No named entities found._");
    lines.push("");
  }

  lines.push("## Numbers & Metrics");
  const metrics = data.metrics;
  if (metrics.length) {
    lines.push("| Metric | Value | Change |");
    lines.push("| --- | --- | --- |");
    for (const m of metrics) {
      const label = m.label || "—";
      const change = m.change || "—";
      lines.push(`| ${label} | ${m.value} | ${change} |`);
    }
  } else {
    lines.push("_No specific metrics found._");
  }
  lines.push("");

  lines.push("## Topics");
  const topics = data.topics;
  if (topics.length) {
    lines.push(topics.map((t) => `\`#${t}\``).join(" "));
  } else {
    lines.push("_No topics identified._");
  }
  lines.push("");

  lines.push("---");
  lines.push(`_Generated by Signal • ${formatTimestamp(when)}_`);
  return lines.join("\n");
}
